#!/usr/bin/env python
"""Turn changelog.md + the CI artifact into server/release.js.

changelog.md is the single source of truth for what each version changed; this
just restates it in a form the Worker can serve, so the dashboard can never drift
from the changelog the way a hand-edited copy would.

    python server/gen-release.py path/to/jackz.click-indicators.geode

The published version is read out of the artifact's own mod.json, not the repo's.
The repo is usually a version ahead of whatever CI last built, and shipping a
build while the site advertises the next version's notes is exactly the mixup
that had a tester chasing bugs in a binary that never contained the fix.

Writes server/release.js and copies the artifact to server/release/, where
wrangler bundles it into the Worker.
"""
import hashlib
import json
import os
import re
import shutil
import sys
import datetime
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse_changelog(path):
    """[{version, notes:[...]}] in file order (newest first)."""
    out = []
    cur = None
    with open(path, encoding="utf-8") as f:
        for line in f:
            head = re.match(r"^##\s+(v\d+\.\d+\.\d+)\s*$", line.strip())
            if head:
                cur = {"version": head.group(1), "notes": []}
                out.append(cur)
                continue
            if cur is None:
                continue
            if line.startswith("- "):
                cur["notes"].append(line[2:].strip())
            elif line.startswith("  ") and line.strip() and cur["notes"]:
                cur["notes"][-1] += " " + line.strip()   # wrapped bullet
    return out


def version_in_artifact(path):
    with zipfile.ZipFile(path) as z:
        names = [n for n in z.namelist() if n.lower() == "mod.json"]
        if not names:
            raise SystemExit("that .geode has no mod.json inside - is it the GitHub "
                             "artifact zip rather than the mod itself?")
        return json.loads(z.read(names[0]).decode("utf-8"))["version"]


def main():
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    artifact = sys.argv[1]
    if not os.path.isfile(artifact):
        print("no such file: " + artifact, file=sys.stderr)
        return 2

    version = version_in_artifact(artifact)

    history = parse_changelog(os.path.join(ROOT, "changelog.md"))
    if not history:
        print("changelog.md has no '## vX.Y.Z' sections", file=sys.stderr)
        return 1

    idx = next((i for i, h in enumerate(history) if h["version"] == version), None)
    if idx is None:
        print("the artifact is %s but changelog.md has no section for it. "
              "Write the release notes first - the dashboard shows them verbatim."
              % version, file=sys.stderr)
        return 1
    # Never advertise notes for a version nobody can download yet.
    history = history[idx:]

    blob = open(artifact, "rb").read()
    digest = hashlib.sha256(blob).hexdigest()

    dest_dir = os.path.join(ROOT, "server", "release")
    os.makedirs(dest_dir, exist_ok=True)
    shutil.copyfile(artifact, os.path.join(dest_dir, "jackz.click-indicators.geode"))

    latest = dict(history[0])
    latest.update({
        "date": datetime.date.today().isoformat(),
        "size": len(blob),
        "sha256": digest,
        "filename": "jackz.click-indicators.geode",
    })

    body = (
        "// Generated by server/gen-release.py - do not edit by hand.\n"
        "// Source of truth is changelog.md and the published artifact.\n\n"
        "export const LATEST = " + json.dumps(latest, indent=2) + ";\n\n"
        "// Older entries are listed so people can see what they missed, but only\n"
        "// LATEST is downloadable - shipping old binaries means supporting them.\n"
        "export const HISTORY = " + json.dumps(history, indent=2) + ";\n"
    )
    with open(os.path.join(ROOT, "server", "release.js"), "w", encoding="utf-8") as f:
        f.write(body)

    repo_ver = json.load(open(os.path.join(ROOT, "mod.json"), encoding="utf-8"))["version"]
    print("publishing  -> %s (%d bytes, sha256 %s...)" % (version, len(blob), digest[:16]))
    if repo_ver != version:
        print("note: the repo is on %s; this publishes the older %s that CI built."
              % (repo_ver, version))
    return 0


if __name__ == "__main__":
    sys.exit(main())
